import type { Metadata } from "next";
import { Lora, Raleway } from "next/font/google";
import "./globals.css";

/* Type pairing from ui-ux-pro-max --domain typography ("Wellness Calm":
   Lora + Raleway). Distinct from Grand Malindo (Playfair+Inter) and
   Bunda (Calistoga+Karla). Self-hosted via next/font/google. */
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

const SITE_URL = "https://kayonridge.id";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Kayon Ridge — A Timber Villa Retreat Above Lembang",
    template: "%s · Kayon Ridge",
  },
  description:
    "A warm timber villa on a pine-forest ridge above Lembang, West Java. The fireplace is always lit, the coffee is local, the valley does the rest. A place to exhale.",
  keywords: [
    "Kayon Ridge",
    "Lembang villa",
    "Bandung mountain retreat",
    "pine forest cabin",
    "tea garden villa",
    "West Java highland stay",
  ],
  authors: [{ name: "Kayon Ridge" }],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Kayon Ridge",
    title: "Kayon Ridge — A Timber Villa Retreat Above Lembang",
    description:
      "A warm timber house on the ridge where the fireplace is always lit and the mountain does the rest. Pine forest, tea gardens, and the valley below — above Lembang, Bandung.",
    // The 1200x630 image is generated by app/opengraph-image.tsx (ImageResponse).
  },
  twitter: {
    card: "summary_large_image",
    title: "Kayon Ridge — A Timber Villa Retreat Above Lembang",
    description:
      "Wood-smoke, mountain air, and a warm room. A pine-ridge villa above Lembang, West Java.",
    // twitter image also served by app/opengraph-image.tsx via Next metadata.
  },
  // Favicon + apple icon are generated by app/icon.tsx and app/apple-icon.tsx.
  // If a brand PNG is dropped in /public, swap the icons field to point at it.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-paper text-ink">
        {children}
      </body>
    </html>
  );
}
